// +build !ignore_autogenerated

/*
Copyright 2018 The Pharmer Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	etcddiscovery "github.com/etcd-manager/etcd-discovery/apis/etcddiscovery"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_EtcdNode_To_etcddiscovery_EtcdNode,
		Convert_etcddiscovery_EtcdNode_To_v1alpha1_EtcdNode,
		Convert_v1alpha1_JoinCluster_To_etcddiscovery_JoinCluster,
		Convert_etcddiscovery_JoinCluster_To_v1alpha1_JoinCluster,
		Convert_v1alpha1_JoinClusterRequest_To_etcddiscovery_JoinClusterRequest,
		Convert_etcddiscovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest,
		Convert_v1alpha1_JoinClusterResponse_To_etcddiscovery_JoinClusterResponse,
		Convert_etcddiscovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse,
		Convert_v1alpha1_PeerInfo_To_etcddiscovery_PeerInfo,
		Convert_etcddiscovery_PeerInfo_To_v1alpha1_PeerInfo,
		Convert_v1alpha1_Ping_To_etcddiscovery_Ping,
		Convert_etcddiscovery_Ping_To_v1alpha1_Ping,
		Convert_v1alpha1_PingRequest_To_etcddiscovery_PingRequest,
		Convert_etcddiscovery_PingRequest_To_v1alpha1_PingRequest,
		Convert_v1alpha1_PingResponse_To_etcddiscovery_PingResponse,
		Convert_etcddiscovery_PingResponse_To_v1alpha1_PingResponse,
	)
}

func autoConvert_v1alpha1_EtcdNode_To_etcddiscovery_EtcdNode(in *EtcdNode, out *etcddiscovery.EtcdNode, s conversion.Scope) error {
	out.Name = in.Name
	out.PeerUrls = *(*[]string)(unsafe.Pointer(&in.PeerUrls))
	out.ClientUrls = *(*[]string)(unsafe.Pointer(&in.ClientUrls))
	out.QuarantinedClientUrls = *(*[]string)(unsafe.Pointer(&in.QuarantinedClientUrls))
	return nil
}

// Convert_v1alpha1_EtcdNode_To_etcddiscovery_EtcdNode is an autogenerated conversion function.
func Convert_v1alpha1_EtcdNode_To_etcddiscovery_EtcdNode(in *EtcdNode, out *etcddiscovery.EtcdNode, s conversion.Scope) error {
	return autoConvert_v1alpha1_EtcdNode_To_etcddiscovery_EtcdNode(in, out, s)
}

func autoConvert_etcddiscovery_EtcdNode_To_v1alpha1_EtcdNode(in *etcddiscovery.EtcdNode, out *EtcdNode, s conversion.Scope) error {
	out.Name = in.Name
	out.PeerUrls = *(*[]string)(unsafe.Pointer(&in.PeerUrls))
	out.ClientUrls = *(*[]string)(unsafe.Pointer(&in.ClientUrls))
	out.QuarantinedClientUrls = *(*[]string)(unsafe.Pointer(&in.QuarantinedClientUrls))
	return nil
}

// Convert_etcddiscovery_EtcdNode_To_v1alpha1_EtcdNode is an autogenerated conversion function.
func Convert_etcddiscovery_EtcdNode_To_v1alpha1_EtcdNode(in *etcddiscovery.EtcdNode, out *EtcdNode, s conversion.Scope) error {
	return autoConvert_etcddiscovery_EtcdNode_To_v1alpha1_EtcdNode(in, out, s)
}

func autoConvert_v1alpha1_JoinCluster_To_etcddiscovery_JoinCluster(in *JoinCluster, out *etcddiscovery.JoinCluster, s conversion.Scope) error {
	out.Request = (*etcddiscovery.JoinClusterRequest)(unsafe.Pointer(in.Request))
	out.Response = (*etcddiscovery.JoinClusterResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_JoinCluster_To_etcddiscovery_JoinCluster is an autogenerated conversion function.
func Convert_v1alpha1_JoinCluster_To_etcddiscovery_JoinCluster(in *JoinCluster, out *etcddiscovery.JoinCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinCluster_To_etcddiscovery_JoinCluster(in, out, s)
}

func autoConvert_etcddiscovery_JoinCluster_To_v1alpha1_JoinCluster(in *etcddiscovery.JoinCluster, out *JoinCluster, s conversion.Scope) error {
	out.Request = (*JoinClusterRequest)(unsafe.Pointer(in.Request))
	out.Response = (*JoinClusterResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_etcddiscovery_JoinCluster_To_v1alpha1_JoinCluster is an autogenerated conversion function.
func Convert_etcddiscovery_JoinCluster_To_v1alpha1_JoinCluster(in *etcddiscovery.JoinCluster, out *JoinCluster, s conversion.Scope) error {
	return autoConvert_etcddiscovery_JoinCluster_To_v1alpha1_JoinCluster(in, out, s)
}

func autoConvert_v1alpha1_JoinClusterRequest_To_etcddiscovery_JoinClusterRequest(in *JoinClusterRequest, out *etcddiscovery.JoinClusterRequest, s conversion.Scope) error {
	out.LeadershipToken = in.LeadershipToken
	out.ClusterName = in.ClusterName
	out.ClusterToken = in.ClusterToken
	out.Nodes = *(*[]*etcddiscovery.EtcdNode)(unsafe.Pointer(&in.Nodes))
	out.AddNode = (*etcddiscovery.EtcdNode)(unsafe.Pointer(in.AddNode))
	out.EtcdVersion = in.EtcdVersion
	return nil
}

// Convert_v1alpha1_JoinClusterRequest_To_etcddiscovery_JoinClusterRequest is an autogenerated conversion function.
func Convert_v1alpha1_JoinClusterRequest_To_etcddiscovery_JoinClusterRequest(in *JoinClusterRequest, out *etcddiscovery.JoinClusterRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinClusterRequest_To_etcddiscovery_JoinClusterRequest(in, out, s)
}

func autoConvert_etcddiscovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest(in *etcddiscovery.JoinClusterRequest, out *JoinClusterRequest, s conversion.Scope) error {
	out.LeadershipToken = in.LeadershipToken
	out.ClusterName = in.ClusterName
	out.ClusterToken = in.ClusterToken
	out.Nodes = *(*[]*EtcdNode)(unsafe.Pointer(&in.Nodes))
	out.AddNode = (*EtcdNode)(unsafe.Pointer(in.AddNode))
	out.EtcdVersion = in.EtcdVersion
	return nil
}

// Convert_etcddiscovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest is an autogenerated conversion function.
func Convert_etcddiscovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest(in *etcddiscovery.JoinClusterRequest, out *JoinClusterRequest, s conversion.Scope) error {
	return autoConvert_etcddiscovery_JoinClusterRequest_To_v1alpha1_JoinClusterRequest(in, out, s)
}

func autoConvert_v1alpha1_JoinClusterResponse_To_etcddiscovery_JoinClusterResponse(in *JoinClusterResponse, out *etcddiscovery.JoinClusterResponse, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_JoinClusterResponse_To_etcddiscovery_JoinClusterResponse is an autogenerated conversion function.
func Convert_v1alpha1_JoinClusterResponse_To_etcddiscovery_JoinClusterResponse(in *JoinClusterResponse, out *etcddiscovery.JoinClusterResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinClusterResponse_To_etcddiscovery_JoinClusterResponse(in, out, s)
}

func autoConvert_etcddiscovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse(in *etcddiscovery.JoinClusterResponse, out *JoinClusterResponse, s conversion.Scope) error {
	return nil
}

// Convert_etcddiscovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse is an autogenerated conversion function.
func Convert_etcddiscovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse(in *etcddiscovery.JoinClusterResponse, out *JoinClusterResponse, s conversion.Scope) error {
	return autoConvert_etcddiscovery_JoinClusterResponse_To_v1alpha1_JoinClusterResponse(in, out, s)
}

func autoConvert_v1alpha1_PeerInfo_To_etcddiscovery_PeerInfo(in *PeerInfo, out *etcddiscovery.PeerInfo, s conversion.Scope) error {
	out.Id = in.Id
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	return nil
}

// Convert_v1alpha1_PeerInfo_To_etcddiscovery_PeerInfo is an autogenerated conversion function.
func Convert_v1alpha1_PeerInfo_To_etcddiscovery_PeerInfo(in *PeerInfo, out *etcddiscovery.PeerInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_PeerInfo_To_etcddiscovery_PeerInfo(in, out, s)
}

func autoConvert_etcddiscovery_PeerInfo_To_v1alpha1_PeerInfo(in *etcddiscovery.PeerInfo, out *PeerInfo, s conversion.Scope) error {
	out.Id = in.Id
	out.Addresses = *(*[]string)(unsafe.Pointer(&in.Addresses))
	return nil
}

// Convert_etcddiscovery_PeerInfo_To_v1alpha1_PeerInfo is an autogenerated conversion function.
func Convert_etcddiscovery_PeerInfo_To_v1alpha1_PeerInfo(in *etcddiscovery.PeerInfo, out *PeerInfo, s conversion.Scope) error {
	return autoConvert_etcddiscovery_PeerInfo_To_v1alpha1_PeerInfo(in, out, s)
}

func autoConvert_v1alpha1_Ping_To_etcddiscovery_Ping(in *Ping, out *etcddiscovery.Ping, s conversion.Scope) error {
	out.Request = (*etcddiscovery.PingRequest)(unsafe.Pointer(in.Request))
	out.Response = (*etcddiscovery.PingResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_Ping_To_etcddiscovery_Ping is an autogenerated conversion function.
func Convert_v1alpha1_Ping_To_etcddiscovery_Ping(in *Ping, out *etcddiscovery.Ping, s conversion.Scope) error {
	return autoConvert_v1alpha1_Ping_To_etcddiscovery_Ping(in, out, s)
}

func autoConvert_etcddiscovery_Ping_To_v1alpha1_Ping(in *etcddiscovery.Ping, out *Ping, s conversion.Scope) error {
	out.Request = (*PingRequest)(unsafe.Pointer(in.Request))
	out.Response = (*PingResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_etcddiscovery_Ping_To_v1alpha1_Ping is an autogenerated conversion function.
func Convert_etcddiscovery_Ping_To_v1alpha1_Ping(in *etcddiscovery.Ping, out *Ping, s conversion.Scope) error {
	return autoConvert_etcddiscovery_Ping_To_v1alpha1_Ping(in, out, s)
}

func autoConvert_v1alpha1_PingRequest_To_etcddiscovery_PingRequest(in *PingRequest, out *etcddiscovery.PingRequest, s conversion.Scope) error {
	out.Info = (*etcddiscovery.PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_v1alpha1_PingRequest_To_etcddiscovery_PingRequest is an autogenerated conversion function.
func Convert_v1alpha1_PingRequest_To_etcddiscovery_PingRequest(in *PingRequest, out *etcddiscovery.PingRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_PingRequest_To_etcddiscovery_PingRequest(in, out, s)
}

func autoConvert_etcddiscovery_PingRequest_To_v1alpha1_PingRequest(in *etcddiscovery.PingRequest, out *PingRequest, s conversion.Scope) error {
	out.Info = (*PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_etcddiscovery_PingRequest_To_v1alpha1_PingRequest is an autogenerated conversion function.
func Convert_etcddiscovery_PingRequest_To_v1alpha1_PingRequest(in *etcddiscovery.PingRequest, out *PingRequest, s conversion.Scope) error {
	return autoConvert_etcddiscovery_PingRequest_To_v1alpha1_PingRequest(in, out, s)
}

func autoConvert_v1alpha1_PingResponse_To_etcddiscovery_PingResponse(in *PingResponse, out *etcddiscovery.PingResponse, s conversion.Scope) error {
	out.Info = (*etcddiscovery.PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_v1alpha1_PingResponse_To_etcddiscovery_PingResponse is an autogenerated conversion function.
func Convert_v1alpha1_PingResponse_To_etcddiscovery_PingResponse(in *PingResponse, out *etcddiscovery.PingResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_PingResponse_To_etcddiscovery_PingResponse(in, out, s)
}

func autoConvert_etcddiscovery_PingResponse_To_v1alpha1_PingResponse(in *etcddiscovery.PingResponse, out *PingResponse, s conversion.Scope) error {
	out.Info = (*PeerInfo)(unsafe.Pointer(in.Info))
	return nil
}

// Convert_etcddiscovery_PingResponse_To_v1alpha1_PingResponse is an autogenerated conversion function.
func Convert_etcddiscovery_PingResponse_To_v1alpha1_PingResponse(in *etcddiscovery.PingResponse, out *PingResponse, s conversion.Scope) error {
	return autoConvert_etcddiscovery_PingResponse_To_v1alpha1_PingResponse(in, out, s)
}
